### ISSUE TITLE
SDAudioSnippet.save_audio_to_file() crashes if no temp directory exists

### ISSUE THREAD

**Issue by brentlyjr** [brentlyjr/rosie#10]
Let's talk this one through next time live. I was going to fix this bug, but don't think I understand your conventions yet to make the code fix in the proper way. IE, I don't understand the semantic difference between the classes SDAudioSnippet and AudioSnippet.

**Comment by brentlyjr** [comment]
I did a completely fresh clone from main into a new directory to reproduce this error. IE, the temp directory does not exist under "rosie" yet.

**Comment by shusterbaby2** [comment]
So AudioSnippet is a virtual class. It's designed as the general structure
and exposes the key methods that would be implemented.  However, since the
implementation details are so dependent on whatever sound library we are
using, the expectation is that we would subclass AudioSnippet for whatever
sound library we are using.  That's why I originally created one called
PyAudioSnippet  (for PyAudio sound library).  Then when I realized it was
not an ideal library, I created a new on subclass called SDAudioSnippet to
utilize the sounddevice library.

You would never call an AudioSnippet directly, always utilize one of the
subclasses.

Let me know what you think
